import { NextResponse } from "next/server";
import fs from "fs";
import path from "path";
import Papa from "papaparse";

export async function GET(request) {
  const { searchParams } = new URL(request.url);
  const date = searchParams.get("date");

  try {
    // Path to the CSV file
    // In a real implementation, you would fetch from GitHub API
    // For now, we'll read from the local file system for development
    const filePath = path.join(
      process.cwd(),
      "public",
      "data",
      "visitor_counts.csv"
    );

    // Check if file exists
    if (!fs.existsSync(filePath)) {
      // For development, provide mock data if file doesn't exist
      console.warn("CSV file not found, using mock data");
      return NextResponse.json(getMockData(date));
    }

    // Read and parse the CSV file
    const fileContent = fs.readFileSync(filePath, "utf8");
    const result = Papa.parse(fileContent, {
      header: true,
      dynamicTyping: true,
      skipEmptyLines: true,
    });

    if (result.errors && result.errors.length > 0) {
      console.error("Error parsing CSV:", result.errors);
      throw new Error("Failed to parse CSV data");
    }

    // Filter data for the requested date
    const filteredData = date
      ? result.data.filter((row) => row.timestamp.startsWith(date))
      : result.data;

    // Transform data for the frontend
    const formattedData = filteredData.map((row) => ({
      timestamp: row.timestamp,
      time: row.timestamp.split(" ")[1].substring(0, 5),
      visitors: row.visitor_count,
      temperature: row.temperature,
      weather_category: row.weather_category,
      is_raining: row.is_raining,
      is_daytime: row.is_daytime,
      is_holiday: row.is_holiday,
      is_vacation_period: row.is_vacation_period,
      special_date_name: row.special_date_name,
    }));

    return NextResponse.json(formattedData);
  } catch (error) {
    console.error("API error:", error);
    return NextResponse.json(
      { error: "Failed to fetch visitor data" },
      { status: 500 }
    );
  }
}

// Mock data for development
function getMockData(date) {
  // Use the hard-coded sample data from the uploaded text file
  const mockData = [
    // These entries would match what's in your uploaded data
    {
      timestamp: "2025-03-22 07:00:00",
      visitor_count: 0,
      temperature: 7.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 07:15:00",
      visitor_count: 4,
      temperature: 7.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 07:30:00",
      visitor_count: 4,
      temperature: 7.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 07:45:00",
      visitor_count: 4,
      temperature: 7.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 08:00:00",
      visitor_count: 7,
      temperature: 8.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 08:15:00",
      visitor_count: 8,
      temperature: 8.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 08:30:00",
      visitor_count: 9,
      temperature: 8.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 08:45:00",
      visitor_count: 12,
      temperature: 8.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 09:00:00",
      visitor_count: 12,
      temperature: 8.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 09:15:00",
      visitor_count: 14,
      temperature: 9.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 09:30:00",
      visitor_count: 12,
      temperature: 9.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 09:45:00",
      visitor_count: 15,
      temperature: 9.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 10:00:00",
      visitor_count: 15,
      temperature: 10.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 10:15:00",
      visitor_count: 11,
      temperature: 10.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 10:30:00",
      visitor_count: 9,
      temperature: 10.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 10:45:00",
      visitor_count: 12,
      temperature: 10.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 11:00:00",
      visitor_count: 11,
      temperature: 10.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 11:15:00",
      visitor_count: 11,
      temperature: 11.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 11:30:00",
      visitor_count: 11,
      temperature: 11.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 11:45:00",
      visitor_count: 13,
      temperature: 11.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 12:00:00",
      visitor_count: 17,
      temperature: 11.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 12:15:00",
      visitor_count: 14,
      temperature: 11.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 12:30:00",
      visitor_count: 15,
      temperature: 11.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 12:45:00",
      visitor_count: 14,
      temperature: 11.7,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 13:00:00",
      visitor_count: 14,
      temperature: 11.7,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 13:30:00",
      visitor_count: 13,
      temperature: 12.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 13:45:00",
      visitor_count: 11,
      temperature: 12.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 14:15:00",
      visitor_count: 11,
      temperature: 12.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 14:30:00",
      visitor_count: 13,
      temperature: 12.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 14:45:00",
      visitor_count: 14,
      temperature: 12.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 15:00:00",
      visitor_count: 10,
      temperature: 12.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 15:15:00",
      visitor_count: 13,
      temperature: 12.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 15:30:00",
      visitor_count: 13,
      temperature: 12.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 15:45:00",
      visitor_count: 13,
      temperature: 12.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 16:00:00",
      visitor_count: 8,
      temperature: 11.9,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 16:15:00",
      visitor_count: 7,
      temperature: 11.9,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 16:30:00",
      visitor_count: 10,
      temperature: 11.9,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 16:45:00",
      visitor_count: 8,
      temperature: 12.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 17:00:00",
      visitor_count: 8,
      temperature: 12.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 17:15:00",
      visitor_count: 5,
      temperature: 11.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 17:30:00",
      visitor_count: 6,
      temperature: 11.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 17:45:00",
      visitor_count: 7,
      temperature: 11.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 18:00:00",
      visitor_count: 5,
      temperature: 10.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 18:15:00",
      visitor_count: 5,
      temperature: 10.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 18:30:00",
      visitor_count: 5,
      temperature: 10.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 18:45:00",
      visitor_count: 6,
      temperature: 10.8,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 19:00:00",
      visitor_count: 5,
      temperature: 10.8,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-22 19:15:00",
      visitor_count: 4,
      temperature: 9.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "no",
      is_holiday: "no",
      is_vacation_period: "no",
    },
  ];

  // Sample data for March 21, 2025 (yesterday)
  const yesterdayMockData = [
    {
      timestamp: "2025-03-21 07:00:00",
      visitor_count: 0,
      temperature: 7.2,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 07:15:00",
      visitor_count: 2,
      temperature: 7.3,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 07:30:00",
      visitor_count: 3,
      temperature: 7.4,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 08:00:00",
      visitor_count: 5,
      temperature: 7.8,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 09:00:00",
      visitor_count: 10,
      temperature: 8.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 10:00:00",
      visitor_count: 13,
      temperature: 9.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 11:00:00",
      visitor_count: 12,
      temperature: 10.1,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 12:00:00",
      visitor_count: 14,
      temperature: 10.8,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 13:00:00",
      visitor_count: 15,
      temperature: 11.2,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 14:00:00",
      visitor_count: 12,
      temperature: 11.5,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 15:00:00",
      visitor_count: 11,
      temperature: 11.8,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 16:00:00",
      visitor_count: 9,
      temperature: 11.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 17:00:00",
      visitor_count: 7,
      temperature: 11.0,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 18:00:00",
      visitor_count: 6,
      temperature: 10.2,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "yes",
      is_holiday: "no",
      is_vacation_period: "no",
    },
    {
      timestamp: "2025-03-21 19:00:00",
      visitor_count: 4,
      temperature: 9.6,
      weather_category: "clear",
      is_raining: "no",
      is_daytime: "no",
      is_holiday: "no",
      is_vacation_period: "no",
    },
  ];

  // Filter the data based on the requested date
  if (!date) {
    return [...mockData, ...yesterdayMockData];
  }

  if (date === "2025-03-22") {
    return mockData;
  } else if (date === "2025-03-21") {
    return yesterdayMockData;
  } else {
    // Return an empty array for dates we don't have data for
    return [];
  }
}
